"""init

Revision ID: 90e96cf4902f
Revises: 
Create Date: 2025-11-11 14:47:02.616800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e96cf4902f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctions'), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('bid_status', sa.Enum('WAITING_AUCTION_RESULT', 'WON', 'LOST', name='bidstatus'), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=False),
    sa.Column('auction_result_bid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('auction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('damage_pr', sa.String(), nullable=True),
    sa.Column('damage_sec', sa.String(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('engine_size', sa.String(), nullable=True),
    sa.Column('cylinders', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    # ### end Alembic commands ###
