"""add buy_now option

Revision ID: dadf6a610765
Revises: 7c6d6d2edc60
Create Date: 2025-12-29 18:27:28.991961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadf6a610765'
down_revision: Union[str, Sequence[str], None] = '7c6d6d2edc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('is_buy_now', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'is_buy_now', server_default=False)
    # ### end Alembic commands ###
